fail_fast: true

repos:

  - repo: https://github.com/psf/black
    rev: '23.3.0'
    hooks:
      - id: black
        language_version: python3.9
        exclude: ^src\/blockfrost_wrapper\/models.py$

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.265'
    hooks:
      - id: ruff
        exclude: ^src\/blockfrost_wrapper\/models.py$
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.2.0'
    hooks:
      - id: mypy
        exclude: ^src\/blockfrost_wrapper\/models.py$
        additional_dependencies: [types-requests==2.28.11.8]